# Generated by Django 3.0.6 on 2020-07-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('street', models.TextField()),
                ('number', models.CharField(max_length=10)),
                ('neighborhood', models.TextField()),
                ('city', models.TextField()),
                ('uf', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('complement', models.TextField()),
            ],
        ),
    ]
