# Generated by Django 3.0.6 on 2020-07-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
