# Generated by Django 3.0.6 on 2020-07-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200702_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='uf',
            field=models.TextField(),
        ),
    ]
